pipeline {
    agent {
        docker {
            image 'python:3.11'
        }
    }


    environment {
        VENV_DIR = "venv"
    }

    triggers {
        // Poll repo every 5 minutes
        pollSCM('H/5 * * * *')
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Lewis-Murimi/alx-backend-python.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Set up Python') {
            steps {
                sh '''
                python3 -m venv ${VENV_DIR}
                . ${VENV_DIR}/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                pip install pytest
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . ${VENV_DIR}/bin/activate
                pytest --junitxml=report.xml
                '''
            }
            post {
                always {
                    junit 'report.xml'
                }
            }
        }
    }
}
